apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xazuresubscriptions.example.io
spec:
  scope: Namespaced
  group: example.io
  names:
    kind: AzureSubscription
    plural: azuresubscriptions
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    subscriptionName:
                      type: string
                      description: "Name of the Azure Subscription"
                    displayName:
                      type: string
                      description: "Display name of the Azure Subscription"
                    billingAccount:
                      type: string
                      description: "Billing account identifier to associate with the subscription"
                    managementGroup:
                      type: string
                      description: "Management Group ID or path to place the subscription under"