# Crossplane v2 note:
# Per Crossplane v2 docs, XRDs use `apiVersion: apiextensions.crossplane.io/v2`
# and you should set `spec.scope` (recommended default in v2 is `Namespaced`).
# See: https://docs.crossplane.io/latest/composition/composite-resource-definitions/
apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: xazuresubscriptions.example.io
spec:
  scope: Namespaced
  group: example.io
  names:
    kind: XAzureSubscription
    plural: xazuresubscriptions
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    subscriptionName:
                      type: string
                      description: Name of the Azure Subscription
                    billingAccountId:
                      type: string
                      description: Azure Billing Account ID
                    workload:
                      type: string
                      enum:
                        - Production
                        - DevTest
                      description: Type of workload for the subscription
                    environment:
                      type: string
                      enum:
                        - dev
                        - staging
                        - prod
                      description: Environment designation
                    tags:
                      type: object
                      additionalProperties:
                        type: string
                      description: Additional tags for the subscription
                    defaultResourceGroup:
                      type: object
                      properties:
                        name:
                          type: string
                        location:
                          type: string
                          default: westeurope
                      required:
                        - name
                  required:
                    - subscriptionName
                    - billingAccountId
                    - workload
                    - environment
              required:
                - parameters
            status:
              type: object
              properties:
                subscriptionId:
                  type: string
                  description: Azure Subscription ID
                state:
                  type: string
                  description: Current state of the subscription
